[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"

[project]
name = "gtsam-jev"
version = "0.1.0"
description = "Discrete factors for GTSAM from TypeSafe's Jev"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "MIT"}
authors = [{name = "Jash Shah"}]
dependencies = ["gtsam-develop", "typesafe-sdk>=0.7"]

[project.optional-dependencies]
test = ["pytest"]

[tool.setuptools]
packages = ["gtsam_jev"]
